name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Send a greeting message
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          👋 Welcome to the AI Bauchi project! Thank you for opening an issue. We’re here to build and grow together. If you have questions or ideas, don’t hesitate to share. The community appreciates your input and effort!

        pr-message: >
          🌟 Thank you for your first pull request! The AI Bauchi team appreciates your contribution to our mission of advancing AI accessibility. We’re excited to review your work and collaborate. Let's make something amazing together!
